"""
Report Generator for Java Migration System

Generates comprehensive migration reports with analysis, results, and recommendations.
"""

import json
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Generates comprehensive migration reports in various formats.
    
    Creates detailed reports including:
    - Migration summary and statistics
    - Applied recipes and changes
    - Error analysis and fixes
    - Recommendations for further action
    - Time tracking and performance metrics
    """
    
    def __init__(self):
        self.report_templates = {
            "markdown": self._generate_markdown_report,
            "json": self._generate_json_report,
            "html": self._generate_html_report
        }
    
    def generate_report(self, migration_state: Dict[str, Any], format: str = "markdown") -> str:
        """
        Generate a comprehensive migration report.
        
        Args:
            migration_state: Complete migration state from the orchestrator
            format: Report format ("markdown", "json", "html")
            
        Returns:
            Path to the generated report file
        """
        logger.info(f"Generating {format} migration report")
        
        try:
            if format not in self.report_templates:
                logger.warning(f"Unknown format {format}, defaulting to markdown")
                format = "markdown"
            
            # Generate report content
            report_content = self.report_templates[format](migration_state)
            
            # Save report to file
            report_path = self._save_report(migration_state, report_content, format)
            
            logger.info(f"Migration report generated: {report_path}")
            return report_path
            
        except Exception as e:
            logger.error(f"Failed to generate migration report: {e}")
            return f"Error generating report: {e}"
    
    def _generate_markdown_report(self, state: Dict[str, Any]) -> str:
        """Generate a markdown format report"""
        
        project_name = state.get("project_name", "Unknown Project")
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        success_status = "✅ SUCCESS" if state.get("success") else "❌ FAILED"
        
        report = f"""# Java Migration Report

**Project:** {project_name}  
**Migration Date:** {timestamp}  
**Status:** {success_status}  
**Duration:** {self._calculate_duration(state)}

## Executive Summary

This report documents the automated migration of a Java project to Java 21 with Spring Boot 3.x and Jakarta EE compatibility using an intelligent agent-based system.

### Migration Overview

- **Current Phase:** {state.get("current_phase", "unknown")}
- **Completed Phases:** {len(state.get("completed_phases", []))}
- **Applied Recipes:** {len(state.get("applied_recipes", []))}
- **Fixes Applied:** {len(state.get("fixes_applied", []))}
- **Remaining Errors:** {len(state.get("compilation_errors", []))}
- **Test Failures:** {len(state.get("test_failures", []))}

## Project Analysis

### Repository Information
- **Path:** {state.get("repository_path", "N/A")}
- **Current Java Version:** {state.get("current_java_version", "Unknown")}
- **Migration Complexity:** {state.get("migration_complexity", "Unknown")}
- **Dependencies:** {len(state.get("dependencies", []))}

## Migration Workflow

The following phases were executed:

{self._generate_phase_summary(state)}

## Applied Changes

### OpenRewrite Recipes Applied

{self._generate_recipes_section(state)}

### Code Fixes Applied

{self._generate_fixes_section(state)}

## Issues and Resolutions

### Compilation Errors

{self._generate_errors_section(state.get("compilation_errors", []))}

### Test Failures

{self._generate_errors_section(state.get("test_failures", []))}

## Agent Communications

### LLM Decisions and Analysis

{self._generate_messages_section(state)}

## Performance Metrics

{self._generate_performance_section(state)}

## Configuration Used

{self._generate_config_section(state)}

## Recommendations

{self._generate_recommendations(state)}

## Next Steps

{self._generate_next_steps(state)}

---

*Report generated by Intelligent Java Migration System*  
*Generated at {timestamp}*  
*System Version: 1.0*
"""
        
        return report
    
    def _generate_json_report(self, state: Dict[str, Any]) -> str:
        """Generate a JSON format report"""
        
        report_data = {
            "metadata": {
                "project_name": state.get("project_name", "Unknown"),
                "generation_time": datetime.now().isoformat(),
                "report_version": "1.0",
                "migration_system": "Intelligent Java Migration System"
            },
            "summary": {
                "success": state.get("success", False),
                "current_phase": state.get("current_phase", "unknown"),
                "completed_phases": state.get("completed_phases", []),
                "duration": self._calculate_duration(state),
                "requires_human_intervention": state.get("requires_human_intervention", False)
            },
            "project_analysis": {
                "repository_path": state.get("repository_path"),
                "current_java_version": state.get("current_java_version"),
                "migration_complexity": state.get("migration_complexity"),
                "dependencies": state.get("dependencies", [])
            },
            "migration_results": {
                "applied_recipes": state.get("applied_recipes", []),
                "fixes_applied": state.get("fixes_applied", []),
                "compilation_errors": state.get("compilation_errors", []),
                "test_failures": state.get("test_failures", [])
            },
            "agent_communications": [
                {
                    "type": msg.__class__.__name__,
                    "content": msg.content,
                    "timestamp": getattr(msg, 'timestamp', None)
                }
                for msg in state.get("messages", [])
            ],
            "configuration": {
                "target_java_version": getattr(state.get("config"), "target_java_version", None),
                "target_spring_version": getattr(state.get("config"), "target_spring_version", None),
                "enabled_features": {
                    "jakarta_migration": getattr(state.get("config"), "enable_jakarta_migration", None),
                    "junit5_migration": getattr(state.get("config"), "enable_junit5_migration", None),
                    "backup_enabled": getattr(state.get("config"), "backup_enabled", None)
                }
            },
            "performance": {
                "start_time": state.get("start_time"),
                "end_time": state.get("end_time"),
                "total_duration_seconds": self._calculate_duration_seconds(state)
            },
            "recommendations": self._generate_recommendations_data(state)
        }
        
        return json.dumps(report_data, indent=2, default=str)
    
    def _generate_html_report(self, state: Dict[str, Any]) -> str:
        """Generate an HTML format report"""
        
        project_name = state.get("project_name", "Unknown Project")
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        success_status = "SUCCESS" if state.get("success") else "FAILED"
        success_class = "success" if state.get("success") else "failure"
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Java Migration Report - {project_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; line-height: 1.6; }}
        .header {{ background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 30px; }}
        .success {{ color: #28a745; }} .failure {{ color: #dc3545; }}
        .section {{ margin-bottom: 30px; }}
        .metrics {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }}
        .metric {{ background: #f8f9fa; padding: 15px; border-radius: 6px; text-align: center; }}
        .metric-value {{ font-size: 24px; font-weight: bold; color: #007bff; }}
        .list-item {{ margin: 8px 0; padding: 8px; background: #f8f9fa; border-radius: 4px; }}
        pre {{ background: #f8f9fa; padding: 15px; border-radius: 6px; overflow-x: auto; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #f8f9fa; font-weight: 600; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Java Migration Report</h1>
        <p><strong>Project:</strong> {project_name}</p>
        <p><strong>Date:</strong> {timestamp}</p>
        <p><strong>Status:</strong> <span class="{success_class}">{success_status}</span></p>
        <p><strong>Duration:</strong> {self._calculate_duration(state)}</p>
    </div>

    <div class="section">
        <h2>Migration Metrics</h2>
        <div class="metrics">
            <div class="metric">
                <div class="metric-value">{len(state.get("completed_phases", []))}</div>
                <div>Phases Completed</div>
            </div>
            <div class="metric">
                <div class="metric-value">{len(state.get("applied_recipes", []))}</div>
                <div>Recipes Applied</div>
            </div>
            <div class="metric">
                <div class="metric-value">{len(state.get("fixes_applied", []))}</div>
                <div>Fixes Applied</div>
            </div>
            <div class="metric">
                <div class="metric-value">{len(state.get("compilation_errors", []))}</div>
                <div>Remaining Errors</div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Applied Changes</h2>
        <h3>OpenRewrite Recipes</h3>
        {self._generate_html_list(state.get("applied_recipes", []))}
        
        <h3>Code Fixes</h3>
        {self._generate_html_list(state.get("fixes_applied", []))}
    </div>

    <div class="section">
        <h2>Issues</h2>
        <h3>Compilation Errors ({len(state.get("compilation_errors", []))})</h3>
        {self._generate_html_list(state.get("compilation_errors", []))}
        
        <h3>Test Failures ({len(state.get("test_failures", []))})</h3>
        {self._generate_html_list(state.get("test_failures", []))}
    </div>

    <div class="section">
        <h2>Configuration</h2>
        <pre>{self._format_config_for_html(state)}</pre>
    </div>

    <div class="section">
        <h2>Recommendations</h2>
        {self._generate_html_recommendations(state)}
    </div>

    <footer style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; color: #666;">
        <p>Report generated by Intelligent Java Migration System at {timestamp}</p>
    </footer>
</body>
</html>"""
        
        return html
    
    def _save_report(self, state: Dict[str, Any], content: str, format: str) -> str:
        """Save report content to file"""
        
        project_name = state.get("project_name", "unknown_project")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Determine file extension
        extensions = {"markdown": "md", "json": "json", "html": "html"}
        ext = extensions.get(format, "txt")
        
        # Generate filename
        filename = f"migration-report-{project_name}-{timestamp}.{ext}"
        
        # Determine save location
        repo_path = state.get("repository_path")
        if repo_path and Path(repo_path).exists():
            save_path = Path(repo_path) / filename
        else:
            save_path = Path.cwd() / filename
        
        try:
            # Write report to file
            with open(save_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            return str(save_path)
            
        except Exception as e:
            logger.error(f"Failed to save report: {e}")
            # Fallback to temp file
            import tempfile
            with tempfile.NamedTemporaryFile(mode='w', suffix=f'.{ext}', delete=False) as f:
                f.write(content)
                return f.name
    
    # Helper methods for report sections
    
    def _calculate_duration(self, state: Dict[str, Any]) -> str:
        """Calculate migration duration"""
        start_time = state.get("start_time")
        end_time = state.get("end_time")
        
        if not start_time:
            return "Unknown"
        
        if not end_time:
            return "In progress"
        
        try:
            start = datetime.fromisoformat(start_time)
            end = datetime.fromisoformat(end_time)
            duration = end - start
            
            # Format duration nicely
            total_seconds = duration.total_seconds()
            hours = int(total_seconds // 3600)
            minutes = int((total_seconds % 3600) // 60)
            seconds = int(total_seconds % 60)
            
            if hours > 0:
                return f"{hours}h {minutes}m {seconds}s"
            elif minutes > 0:
                return f"{minutes}m {seconds}s"
            else:
                return f"{seconds}s"
                
        except Exception:
            return "Unknown"
    
    def _calculate_duration_seconds(self, state: Dict[str, Any]) -> Optional[float]:
        """Calculate migration duration in seconds"""
        start_time = state.get("start_time")
        end_time = state.get("end_time")
        
        if not start_time or not end_time:
            return None
        
        try:
            start = datetime.fromisoformat(start_time)
            end = datetime.fromisoformat(end_time)
            return (end - start).total_seconds()
        except Exception:
            return None
    
    def _generate_phase_summary(self, state: Dict[str, Any]) -> str:
        """Generate phase summary section"""
        completed_phases = state.get("completed_phases", [])
        current_phase = state.get("current_phase", "unknown")
        
        phase_descriptions = {
            "initialization": "Project validation and setup",
            "analysis": "Repository structure and dependency analysis",
            "planning": "Migration strategy and recipe selection",
            "execution": "OpenRewrite recipe application",
            "error_fixing": "Compilation error resolution",
            "validation": "Test execution and validation",
            "complete": "Final report generation",
            "human_escalation": "Human intervention required"
        }
        
        summary = []
        
        for phase in completed_phases:
            description = phase_descriptions.get(phase, "Unknown phase")
            summary.append(f"- ✅ **{phase.replace('_', ' ').title()}**: {description}")
        
        if current_phase not in completed_phases:
            description = phase_descriptions.get(current_phase, "Unknown phase")
            summary.append(f"- 🔄 **{current_phase.replace('_', ' ').title()}**: {description} (In Progress)")
        
        return "\n".join(summary) if summary else "No phases completed"
    
    def _generate_recipes_section(self, state: Dict[str, Any]) -> str:
        """Generate applied recipes section"""
        recipes = state.get("applied_recipes", [])
        
        if not recipes:
            return "No OpenRewrite recipes were applied."
        
        return "\n".join(f"- {recipe}" for recipe in recipes)
    
    def _generate_fixes_section(self, state: Dict[str, Any]) -> str:
        """Generate applied fixes section"""
        fixes = state.get("fixes_applied", [])
        
        if not fixes:
            return "No manual fixes were applied."
        
        return "\n".join(f"- {fix}" for fix in fixes)
    
    def _generate_errors_section(self, errors: List[str]) -> str:
        """Generate errors section"""
        if not errors:
            return "No errors found."
        
        if len(errors) <= 5:
            return "\n".join(f"- {error}" for error in errors)
        else:
            shown_errors = "\n".join(f"- {error}" for error in errors[:5])
            return f"{shown_errors}\n- ... and {len(errors) - 5} more errors"
    
    def _generate_messages_section(self, state: Dict[str, Any]) -> str:
        """Generate agent messages section"""
        messages = state.get("messages", [])
        
        if not messages:
            return "No agent communications logged."
        
        summary = []
        for msg in messages[-10:]:  # Show last 10 messages
            msg_type = msg.__class__.__name__ if hasattr(msg, '__class__') else "Message"
            content = getattr(msg, 'content', str(msg))[:200]  # Limit content length
            summary.append(f"- **{msg_type}**: {content}...")
        
        return "\n".join(summary)
    
    def _generate_performance_section(self, state: Dict[str, Any]) -> str:
        """Generate performance metrics section"""
        duration = self._calculate_duration(state)
        
        metrics = [
            f"- **Total Duration**: {duration}",
            f"- **Phases Completed**: {len(state.get('completed_phases', []))}",
            f"- **Recipes Applied**: {len(state.get('applied_recipes', []))}",
            f"- **Fixes Applied**: {len(state.get('fixes_applied', []))}"
        ]
        
        return "\n".join(metrics)
    
    def _generate_config_section(self, state: Dict[str, Any]) -> str:
        """Generate configuration section"""
        config = state.get("config")
        
        if not config:
            return "No configuration information available."
        
        config_items = [
            f"- **Target Java Version**: {getattr(config, 'target_java_version', 'N/A')}",
            f"- **Target Spring Version**: {getattr(config, 'target_spring_version', 'N/A')}",
            f"- **Target Spring Boot Version**: {getattr(config, 'target_spring_boot_version', 'N/A')}",
            f"- **Jakarta Migration Enabled**: {getattr(config, 'enable_jakarta_migration', 'N/A')}",
            f"- **JUnit 5 Migration Enabled**: {getattr(config, 'enable_junit5_migration', 'N/A')}",
            f"- **Backup Enabled**: {getattr(config, 'backup_enabled', 'N/A')}",
            f"- **Dry Run**: {getattr(config, 'dry_run', 'N/A')}"
        ]
        
        return "\n".join(config_items)
    
    def _generate_recommendations(self, state: Dict[str, Any]) -> str:
        """Generate recommendations section"""
        recommendations = []
        
        # General recommendations based on state
        if state.get("success"):
            recommendations.extend([
                "1. **Review Changes**: Carefully review all automated changes before deploying to production",
                "2. **Extended Testing**: Run comprehensive integration and performance tests",
                "3. **Update Documentation**: Update project documentation to reflect Java 21 requirements",
                "4. **CI/CD Updates**: Update build pipelines to use Java 21"
            ])
        else:
            recommendations.extend([
                "1. **Review Errors**: Address remaining compilation errors and test failures",
                "2. **Manual Review**: Some changes may require manual intervention",
                "3. **Incremental Migration**: Consider applying recipes incrementally if issues persist"
            ])
        
        # Add specific recommendations based on issues
        if state.get("compilation_errors"):
            recommendations.append("4. **Compilation Issues**: Focus on resolving compilation errors before proceeding")
        
        if state.get("test_failures"):
            recommendations.append("5. **Test Failures**: Update test cases to work with new Java 21 and framework versions")
        
        if state.get("requires_human_intervention"):
            recommendations.append("6. **Human Review Required**: Some issues require expert analysis and manual fixes")
        
        return "\n".join(recommendations) if recommendations else "No specific recommendations at this time."
    
    def _generate_next_steps(self, state: Dict[str, Any]) -> str:
        """Generate next steps section"""
        if state.get("success"):
            return """1. Deploy to staging environment for testing
2. Run performance benchmarks
3. Update deployment documentation
4. Schedule production deployment
5. Monitor application performance post-migration"""
        else:
            return """1. Address remaining compilation errors
2. Fix failing tests
3. Review agent recommendations
4. Consider manual intervention for complex issues
5. Re-run migration after fixes"""
    
    def _generate_recommendations_data(self, state: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate recommendations data for JSON format"""
        recommendations = []
        
        if state.get("success"):
            recommendations = [
                {"priority": "high", "category": "testing", "action": "Run comprehensive integration tests"},
                {"priority": "medium", "category": "documentation", "action": "Update project documentation"},
                {"priority": "medium", "category": "deployment", "action": "Update CI/CD pipelines"}
            ]
        else:
            recommendations = [
                {"priority": "high", "category": "errors", "action": "Address compilation errors"},
                {"priority": "high", "category": "testing", "action": "Fix failing tests"},
                {"priority": "medium", "category": "review", "action": "Manual code review required"}
            ]
        
        return recommendations
    
    def _generate_html_list(self, items: List[str]) -> str:
        """Generate HTML list from string items"""
        if not items:
            return "<p>None</p>"
        
        list_items = "".join(f"<div class='list-item'>{item}</div>" for item in items[:10])
        if len(items) > 10:
            list_items += f"<div class='list-item'>... and {len(items) - 10} more items</div>"
        
        return f"<div>{list_items}</div>"
    
    def _format_config_for_html(self, state: Dict[str, Any]) -> str:
        """Format configuration for HTML display"""
        config = state.get("config")
        
        if not config:
            return "No configuration available"
        
        config_dict = {
            "target_java_version": getattr(config, 'target_java_version', None),
            "target_spring_version": getattr(config, 'target_spring_version', None),
            "target_spring_boot_version": getattr(config, 'target_spring_boot_version', None),
            "enable_jakarta_migration": getattr(config, 'enable_jakarta_migration', None),
            "enable_junit5_migration": getattr(config, 'enable_junit5_migration', None),
            "backup_enabled": getattr(config, 'backup_enabled', None),
            "dry_run": getattr(config, 'dry_run', None)
        }
        
        return json.dumps({k: v for k, v in config_dict.items() if v is not None}, indent=2)
    
    def _generate_html_recommendations(self, state: Dict[str, Any]) -> str:
        """Generate HTML recommendations"""
        recommendations_text = self._generate_recommendations(state)
        
        # Convert markdown-style list to HTML
        lines = recommendations_text.split('\n')
        html_items = []
        
        for line in lines:
            if line.strip().startswith(('1.', '2.', '3.', '4.', '5.', '6.')):
                # Extract the recommendation text
                text = line.strip()[2:].strip()  # Remove number and space
                html_items.append(f"<div class='list-item'>{text}</div>")
        
        return f"<div>{''.join(html_items)}</div>" if html_items else "<p>No recommendations available</p>"